const TEMPLATE_IMPORTS_PLACEHOLDER = "{IMPORTS}";
const TEMPLATE_BODY_PLACEHOLDER = "{BODY}";

export const template = `// This file is autogenerated by "oas-to-joi"
${TEMPLATE_IMPORTS_PLACEHOLDER}

const schema = ${TEMPLATE_BODY_PLACEHOLDER};

export default schema;

`;

const merge = (options: { imports: string; body: string }) => {
  return template
    .replace(TEMPLATE_IMPORTS_PLACEHOLDER, options.imports)
    .replace(TEMPLATE_BODY_PLACEHOLDER, options.body);
};

export default merge;
