type Options = {
  references: Array<string>;
  definitions: Array<string>;
};

const JOI_WORD = "Joi.";
const TEMPLATE_JOI_IMPORT_PLACEHOLDER = `import Joi from "joi";`;
const TEMPLATE_IMPORTS_PLACEHOLDER = "{IMPORTS}";
const TEMPLATE_BODY_PLACEHOLDER = "{BODY}";
const TEMPLATE_JOI_OBJECT = (definitions: Array<string>) =>
  `Joi.object({\n\u0020\u0020${definitions.join(",\n\u0020\u0020")}\n})`;

export const template = `// This file is autogenerated by "oas-to-joi"
${TEMPLATE_IMPORTS_PLACEHOLDER}

const schema = ${TEMPLATE_BODY_PLACEHOLDER};

export default schema;
`;
const merge = (options: Options) => {
  const { references, definitions } = options;
  const needsImportJoi = definitions.toString().includes(JOI_WORD);

  if (needsImportJoi) {
    references.unshift(TEMPLATE_JOI_IMPORT_PLACEHOLDER);
  }

  const body = needsImportJoi
    ? TEMPLATE_JOI_OBJECT(definitions)
    : definitions.join(",");

  return template
    .replace(TEMPLATE_IMPORTS_PLACEHOLDER, references.join("\n"))
    .replace(TEMPLATE_BODY_PLACEHOLDER, body);
};

export default merge;
