const TEMPLATE_IMPORTS_PLACEHOLDER = "{IMPORTS}";
const TEMPLATE_NAME_PLACEHOLDER = "{NAME}";
const TEMPLATE_BODY_PLACEHOLDER = "{BODY}";

export const template = `// This file is autogenerated by "oas-to-joi"
${TEMPLATE_IMPORTS_PLACEHOLDER}

export type ${TEMPLATE_NAME_PLACEHOLDER} = {
${TEMPLATE_BODY_PLACEHOLDER}
};
`;

const merge = (options: { name: string; imports: string; body: string }) => {
  return template
    .replace(TEMPLATE_IMPORTS_PLACEHOLDER, options.imports)
    .replace(TEMPLATE_NAME_PLACEHOLDER, options.name)
    .replace(TEMPLATE_BODY_PLACEHOLDER, options.body);
};

export default merge;
